report_to: wandb
run_name: Qwen2.5-7B-Instruct-1M
model_name_or_path: Qwen/Qwen2.5-7B-Instruct-1M
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
dataset: hevi
template: qwen3_nothink
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
output_dir: saves/Qwen2.5-7B-Instruct-1M/lora/sft
logging_steps: 10
save_strategy: steps
save_steps: 50
save_total_limit: 2
metric_for_best_model: eval_loss
greater_is_better: false
load_best_model_at_end: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-05
num_train_epochs: 10
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
overwrite_output_dir: true
save_safetensors: true
eval_strategy: steps
eval_steps: 50
val_size: 0.1
per_device_eval_batch_size: 1
